launcher/minecract/auth/AccountList.cpp: add missing QIcon include
In member function ‘virtual QVariant AccountList::data(const QModelIndex&, int) const’:
/var/tmp/portage/games-action/prismlauncher-9999/work/prismlauncher-9999/launcher/minecraft/auth/AccountList.cpp:331:35: error: incomplete type ‘QIcon’ used in nested name specifier
  331 |                     return QIcon::fromTheme("noaccount").pixmap(24, 24);
      |

Fixes: fc1e29111bff46ebe9c12277d4edadf7f5f29d8a
Signed-off-by: Alfred Wingate <parona@protonmail.com>